#pragma once
//file for the virtual kb codes help
//////////////////////////////////////////////////////////////////////////
// this file contains help information for the virtual keyboard codes
// from Winuser.h in a comfortable form, ready to copypaste
// 
// The "--" instead of keycode, means that it doest have a defined name
// in header file
// "Reserved" means that the key code is reserved for possible future use.
// 
// "Unassigned" means that the key code exists, but is not assigned to
// any of the keys yet. Will possibly in future.
// 
// "??????" means that it exists and no more information is give, it's 
// undefined.
//////////////////////////////////////////////////////////////////////////
// 
//KEYCODES
/*
  BUTTON                   HEX  DEC  DESCRIPTION

  VK_LBUTTON                01  1    "Left mouse button"
  VK_RBUTTON                02  2    "Right mouse button"
  VK_CANCEL                 03  3    "Control-break processing"
  VK_MBUTTON                04  4    "Middle mouse button (three-button mouse)"
  VK_XBUTTON1               05  5    "Windows 2000: X1 mouse button"
  VK_XBUTTON2               06  6    "Windows 2000: X2 mouse button"
  --                        07  7    "??????"
  VK_BACK                   08  8    "BACKSPACE key"
  VK_TAB                    09  9    "TAB key"
  --                        0A  10   "Reserved"
  --                        0B  11   "Reserved"
  VK_CLEAR                  0C  12   "CLEAR key"
  VK_RETURN                 0D  13   "ENTER key"
  --                        0E  14   "??????"
  --                        0F  15   "??????"
  VK_SHIFT                  10  16   "SHIFT key"
  VK_CONTROL                11  17   "CTRL key"
  VK_MENU                   12  18   "ALT key"
  VK_PAUSE                  13  19   "PAUSE key"
  VK_CAPITAL                14  20   "CAPS LOCK key"
  VK_KANA                   15  21   "IME Kana mode"
  VK_HANGUEL                15  21   "IME Hanguel mode (maintained for compatibility; use VK_HANGUL)"
  VK_HANGUL                 15  21   "IME Hangul mode"
  --                        16  22   "??????"
  VK_JUNJA                  17  23   "IME Junja mode"
  VK_FINAL                  18  24   "IME final mode"
  VK_HANJA                  19  25   "IME Hanja mode"
  VK_KANJI                  19  25   "IME Kanji mode"
  --                        1A  26   "??????"
  VK_ESCAPE                 1B  27   "ESC key"
  VK_CONVERT                1C  28   "IME convert"
  VK_NONCONVERT             1D  29   "IME nonconvert"
  VK_ACCEPT                 1E  30   "IME accept"
  VK_MODECHANGE             1F  31   "IME mode change request"
  VK_SPACE                  20  32   "SPACEBAR"
  VK_PRIOR                  21  33   "PAGE UP key"
  VK_NEXT                   22  34   "PAGE DOWN key"
  VK_END                    23  35   "END key"
  VK_HOME                   24  36   "HOME key"
  VK_LEFT                   25  37   "LEFT ARROW key"
  VK_UP                     26  38   "UP ARROW key"
  VK_RIGHT                  27  39   "RIGHT ARROW key"
  VK_DOWN                   28  40   "DOWN ARROW key"
  VK_SELECT                 29  41   "SELECT key"
  VK_PRINT                  2A  42   "PRINT key"
  VK_EXECUTE                2B  43   "EXECUTE key"
  VK_SNAPSHOT               2C  44   "PRINT SCREEN key"
  VK_INSERT                 2D  45   "INS key"
  VK_DELETE                 2E  46   "DEL key"
  VK_HELP                   2F  47   "HELP key"
  '0'                       30  48   "0 key"
  '1'                       31  49   "1 key"
  '2'                       32  50   "2 key"
  '3'                       33  51   "3 key"
  '4'                       34  52   "4 key"
  '5'                       35  53   "5 key"
  '6'                       36  54   "6 key"
  '7'                       37  55   "7 key"
  '8'                       38  56   "8 key"
  '9'                       39  57   "9 key"
  --                        3A  58   "??????"
  --                        3B  59   "??????"
  --                        3C  60   "??????"
  --                        3D  61   "??????"
  --                        3E  62   "??????"
  --                        3F  63   "??????"
  --                        40  64   "??????"
  'A'                       41  65   "A key"
  'B'                       42  66   "B key"
  'C'                       43  67   "C key"
  'D'                       44  68   "D key"
  'E'                       45  69   "E key"
  'F'                       46  70   "F key"
  'G'                       47  71   "G key"
  'H'                       48  72   "H key"
  'I'                       49  73   "I key"
  'J'                       4A  74   "J key"
  'K'                       4B  75   "K key"
  'L'                       4C  76   "L key"
  'M'                       4D  77   "M key"
  'N'                       4E  78   "N key"
  'O'                       4F  79   "O key"
  'P'                       50  80   "P key"
  'Q'                       51  81   "Q key"
  'R'                       52  82   "R key"
  'S'                       53  83   "S key"
  'T'                       54  84   "T key"
  'U'                       55  85   "U key"
  'V'                       56  86   "V key"
  'W'                       57  87   "W key"
  'X'                       58  88   "X key"
  'Y'                       59  89   "Y key"
  'Z'                       5A  90   "Z key"
  VK_LWIN                   5B  91   "Left Windows key (Microsoft Natural Keyboard)"
  VK_RWIN                   5C  92   "Right Windows key (Microsoft Natural Keyboard)"
  VK_APPS                   5D  93   "Applications key (Microsoft Natural Keyboard)"
  --                        5E  94   "Reserved"
  VK_SLEEP                  5F  95   "Computer Sleep key"
  VK_NUMPAD0                60  96   "Numeric keypad 0 key"
  VK_NUMPAD1                61  97   "Numeric keypad 1 key"
  VK_NUMPAD2                62  98   "Numeric keypad 2 key"
  VK_NUMPAD3                63  99   "Numeric keypad 3 key"
  VK_NUMPAD4                64  100  "Numeric keypad 4 key"
  VK_NUMPAD5                65  101  "Numeric keypad 5 key"
  VK_NUMPAD6                66  102  "Numeric keypad 6 key"
  VK_NUMPAD7                67  103  "Numeric keypad 7 key"
  VK_NUMPAD8                68  104  "Numeric keypad 8 key"
  VK_NUMPAD9                69  105  "Numeric keypad 9 key"
  VK_MULTIPLY               6A  106  "Multiply key"
  VK_ADD                    6B  107  "Add key"
  VK_SEPARATOR              6C  108  "Separator key"
  VK_SUBTRACT               6D  109  "Subtract key"
  VK_DECIMAL                6E  110  "Decimal key"
  VK_DIVIDE                 6F  111  "Divide key"
  VK_F1                     70  112  "F1 key"
  VK_F2                     71  113  "F2 key"
  VK_F3                     72  114  "F3 key"
  VK_F4                     73  115  "F4 key"
  VK_F5                     74  116  "F5 key"
  VK_F6                     75  117  "F6 key"
  VK_F7                     76  118  "F7 key"
  VK_F8                     77  119  "F8 key"
  VK_F9                     78  120  "F9 key"
  VK_F10                    79  121  "F10 key"
  VK_F11                    7A  122  "F11 key"
  VK_F12                    7B  123  "F12 key"
  VK_F13                    7C  124  "F13 key"
  VK_F14                    7D  125  "F14 key"
  VK_F15                    7E  126  "F15 key"
  VK_F16                    7F  127  "F16 key"
  VK_F17                    80  128  "F17 key"
  VK_F18                    81  129  "F18 key"
  VK_F19                    82  130  "F19 key"
  VK_F20                    83  131  "F20 key"
  VK_F21                    84  132  "F21 key"
  VK_F22                    85  133  "F22 key"
  VK_F23                    86  134  "F23 key"
  VK_F24                    87  135  "F24 key"
  --                        88  136  "Unassigned"
  --                        89  137  "Unassigned"
  --                        8A  138  "Unassigned"
  --                        8B  139  "Unassigned"
  --                        8C  140  "Unassigned"
  --                        8D  141  "Unassigned"
  --                        8E  142  "Unassigned"
  --                        8F  143  "Unassigned"
  VK_NUMLOCK                90  144  "NUM LOCK key"
  VK_SCROLL                 91  145  "SCROLL LOCK key"
  --                        92  146  "OEM specific"
  --                        93  147  "OEM specific"
  --                        94  148  "OEM specific"
  --                        95  149  "OEM specific"
  --                        96  150  "OEM specific"
  --                        97  151  "Unassigned"
  --                        98  152  "Unassigned"
  --                        99  153  "Unassigned"
  --                        9A  154  "Unassigned"
  --                        9B  155  "Unassigned"
  --                        9C  156  "Unassigned"
  --                        9D  157  "Unassigned"
  --                        9E  158  "Unassigned"
  --                        9F  159  "Unassigned"
  VK_LSHIFT                 A0  160  "Left SHIFT key"
  VK_RSHIFT                 A1  161  "Right SHIFT key"
  VK_LCONTROL               A2  162  "Left CONTROL key"
  VK_RCONTROL               A3  163  "Right CONTROL key"
  VK_LMENU                  A4  164  "Left MENU key"
  VK_RMENU                  A5  165  "Right MENU key"
  VK_BROWSER_BACK           A6  166  "Windows 2000: Browser Back key"
  VK_BROWSER_FORWARD        A7  167  "Windows 2000: Browser Forward key"
  VK_BROWSER_REFRESH        A8  168  "Windows 2000: Browser Refresh key"
  VK_BROWSER_STOP           A9  169  "Windows 2000: Browser Stop key"
  VK_BROWSER_SEARCH         AA  170  "Windows 2000: Browser Search key"
  VK_BROWSER_FAVORITES      AB  171  "Windows 2000: Browser Favorites key"
  VK_BROWSER_HOME           AC  172  "Windows 2000: Browser Launch and Home key"
  VK_VOLUME_MUTE            AD  173  "Windows 2000: Volume Mute key"
  VK_VOLUME_DOWN            AE  174  "Windows 2000: Volume Down key"
  VK_VOLUME_UP              AF  175  "Windows 2000: Volume Up key"
  VK_MEDIA_NEXT_TRACK       B0  176  "Windows 2000: Next Track key"
  VK_MEDIA_PREV_TRACK       B1  177  "Windows 2000: Previous Track key"
  VK_MEDIA_STOP             B2  178  "Windows 2000: Stop Media key"
  VK_MEDIA_PLAY_PAUSE       B3  179  "Windows 2000: Play/Pause Media key"
  VK_LAUNCH_MAIL            B4  180  "Windows 2000: Launch Mail key"
  VK_LAUNCH_MEDIA_SELECT    B5  181  "Windows 2000: Select Media key"
  VK_LAUNCH_APP1            B6  182  "Windows 2000: Launch Application 1 key"
  VK_LAUNCH_APP2            B7  183  "Windows 2000: Launch Application 2 key"
  --                        B8  184  "Reserved"
  --                        B9  185  "Reserved"
  VK_OEM_1                  BA  186  "Windows 2000: for the US standard keyboard, the ';:' key"
  VK_OEM_PLUS               BB  187  "Windows 2000: for any country/region, the '+' key"
  VK_OEM_COMMA              BC  188  "Windows 2000: for any country/region, the ',' key"
  VK_OEM_MINUS              BD  189  "Windows 2000: for any country/region, the '-' key"
  VK_OEM_PERIOD             BE  190  "Windows 2000: for any country/region, the '.' key"
  VK_OEM_2                  BF  191  "Windows 2000: for the US standard keyboard, the '/?' key"
  VK_OEM_3                  C0  192  "Windows 2000: for the US standard keyboard, the '`~' key"
  --                        C1  193  "Reserved"
  --                        C2  194  "Reserved"
  --                        C3  195  "Reserved"
  --                        C4  196  "Reserved"
  --                        C5  197  "Reserved"
  --                        C6  198  "Reserved"
  --                        C7  199  "Reserved"
  --                        C8  200  "Reserved"
  --                        C9  201  "Reserved"
  --                        CA  202  "Reserved"
  --                        CB  203  "Reserved"
  --                        CC  204  "Reserved"
  --                        CD  205  "Reserved"
  --                        CE  206  "Reserved"
  --                        CF  207  "Reserved"
  --                        D0  208  "Reserved"
  --                        D1  209  "Reserved"
  --                        D2  210  "Reserved"
  --                        D3  211  "Reserved"
  --                        D4  212  "Reserved"
  --                        D5  213  "Reserved"
  --                        D6  214  "Reserved"
  --                        D7  215  "Reserved"
  --                        D8  216  "Unassigned"
  --                        D9  217  "Unassigned"
  --                        DA  218  "Unassigned"
  VK_OEM_4                  DB  219  "Windows 2000: for the US standard keyboard, the '[{' key"
  VK_OEM_5                  DC  220  "Windows 2000: for the US standard keyboard, the '\|' key"
  VK_OEM_6                  DD  221  "Windows 2000: for the US standard keyboard, the ']}' key"
  VK_OEM_7                  DE  222  "Windows 2000: for the US standard keyboard, the 'single-quote/double-quote' key"
  VK_OEM_8                  DF  223  "" ""
  --                        E0  224  "Reserved"
  --                        E1  225  "OEM specific"
  VK_OEM_102                E2  226  "Windows 2000: either the '<>' key or the '\|' key on the RT 102-key keyboard"
  --                        E3  227  "OEM specific"
  --                        E4  228  "OEM specific"
  VK_PROCESSKEY             E5  229  "Windows 95, Windows NT 4.0, and Windows 2000: IME PROCESS key"
  --                        E6  230  "OEM specific"
  VK_PACKET                 E7  231  "Windows 2000: Used to pass Unicode characters as if they were keystrokes. The VK_PACKET key is the low word of a 32-bit Virtual Key value used for non-keyboard input methods. The Unicode character is the high word."
  --                        E8  232  "Unassigned"
  --                        E9  233  "OEM specific"
  --                        EA  234  "OEM specific"
  --                        EB  235  "OEM specific"
  --                        EC  236  "OEM specific"
  --                        ED  237  "OEM specific"
  --                        EE  238  "OEM specific"
  --                        EF  239  "OEM specific"
  --                        F0  240  "OEM specific"
  --                        F2  242  "OEM specific"
  --                        F3  243  "OEM specific"
  --                        F4  244  "OEM specific"
  --                        F5  245  "OEM specific"
  VK_ATTN                   F6  246  "Attn key"
  VK_CRSEL                  F7  247  "CrSel key"
  VK_EXSEL                  F8  248  "ExSel key"
  VK_EREOF                  F9  249  "Erase EOF key"
  VK_PLAY                   FA  250  "Play key"
  VK_ZOOM                   FB  251  "Zoom key"
  VK_NONAME                 FC  252  "Reserved for future use"
  VK_PA1                    FD  253  "PA1 key"
  VK_OEM_CLEAR              FE  254  "Clear key"
  --                        FF  255  "Reserved"
 */
//END OF KEYCODES
//
//////////////////////////////////////////////////////////////////////////


